services:
  database:
    container_name: database
    image: postgres:17.4-alpine3.21
    environment:
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_password
      POSTGRES_DB: local_db
    ports:
      - 5432:5432
